### ISSUE TITLE
odroid c2 issue

### ISSUE THREAD

**Issue by mich2200** [beta68/install_cevdrx11#1]
hi beta thanks for your script 
i have an issue with n2 ubuntu image because i have s905d amlogic box so i tried to modify script and put odroid c2 image and ended up with error in linux-N2 not found .
can u please tell me what else to modify to make it work?

**Comment by beta68** [comment]
hi, you need to find a LINUX distribution which matches your hardware. I think Khadas has an Ubuntu version.
Therefore, you need to change the download link to Khadas and continue my script step-by-step.
