### ISSUE TITLE
X11 hw decode problem 

### ISSUE THREAD

**Issue by mich2200** [beta68/install_cevdrx11#2]
Hi again and sorry for inconvenience
I got your script working and it's really good
So my problem is there is anyway to use wayland instead of x11?
I will explain my problem to be clear
when I use mpv to run any video its stuttering and dropping frames. When I searched for the problem turned out x11 with Mali don't support hardware decoder but wayland do
Any suggestions appreciated

**Comment by beta68** [comment]
This is no inconvenience. I do no think that there is a way to use Wayland with CE 4.9 kernel.
To my opinion Wayland is possible with newer kernels. However, in that case you will use your CoreElec installation.

**Comment by mich2200** [comment]
I will give it a shot thnx.
